server:
  port: 8081

spring:
  application:
    name: simple-mall-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/simple_mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0

app:
  jwt:
    secret: aVeryStrongAndLongSecretKeyForThisSimpleMallProject
    expiration-ms: 86400000